version: 1.0.2-{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
- ps: dotnet restore
build:
  project: Enchilada.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
test: off
artifacts:
- path: src\Enchilada\bin\Release\Enchilada.*.nupkg
- path: src\Enchilada.AspNetCore\bin\Release\Enchilada.AspNetCore.*.nupkg
- path: src\Enchilada.Azure\bin\Release\Enchilada.Azure.*.nupkg
- path: src\Enchilada.Ftp\bin\Release\Enchilada.Ftp.*.nupkg